engines:
  duplication:
    enabled: true
    config:
      languages:
        python:
          mass_threshold: 40
  fixme:
    enabled: false
  radon:
    enabled: false
ratings:
  paths:
   - "**.py"
exclude_paths:
  - test/