language: python
python:
  - "2.7"
env:
  - NET_SNMP_VERSION=5.7.3
services:
  - mysql
before_install:
  # Install build dependencies
  - sudo apt-get update
  - sudo apt-get install -y autoconf libtool make libperl-dev python-dev
  # Download and extract the required version of Net-SNMP
  - wget http://downloads.sourceforge.net/sourceforge/net-snmp/net-snmp-$NET_SNMP_VERSION.tar.gz
  - tar zxvf net-snmp-$NET_SNMP_VERSION.tar.gz
  - cd net-snmp-$NET_SNMP_VERSION
  # Build and install Net-SNMP
  - autoreconf -f -i
  - ./configure
    --prefix=/usr/local
    --enable-ucd-snmp-compatibility
    --enable-ipv6
    --with-default-snmp-version="3"
    --with-sys-contact="root@localhost"
    --with-sys-location="Unknown"
    --with-logfile="/var/log/snmpd.log"
    --with-mib-modules="host misc/ipfwacc ucd-snmp/diskio tunnel ucd-snmp/dlmod"
    --with-persistent-directory="/var/net-snmp"
  - make -j4 NETSNMP_DONT_CHECK_VERSION=1
  - sudo make install
  - sudo ldconfig
  - cd ..
  # Clean up the extracted files
  - rm -rf net-snmp-$NET_SNMP_VERSION
  # Display the build version of Net-SNMP
  - net-snmp-config --version
  # Create MySQL database
  - mysql -e 'CREATE DATABASE IF NOT EXISTS dnsupdate;'
  # Install snmpd for testing stuff...
  - sudo apt-get install -y snmpd
  - sudo cp test/system/snmpd.conf /etc/snmp/snmpd.conf
  - sudo service snmpd restart
install:
  - pip install -r requirements.txt
script: python -m unittest discover
after_sucess:
  - CODECLIMATE_REPO_TOKEN=03b947e9cd250d7f779f49eb7024b4e467543a50b73f15a93e907bbf1f14144b codeclimate-test-reporter
